### ISSUE TITLE
Useless Class?

### ISSUE THREAD

**Issue by yoyo200181** [CS3343Group20/Project#11]
1. Handle.java curFloorHaveAccepedReq()
This class is not called
![image](https://user-images.githubusercontent.com/113662537/196477108-fa5b5162-ceaa-44b0-a4cd-b30e420b606c.png)

2. Handle.java goUp(), goDown()
Classes are not called
![image](https://user-images.githubusercontent.com/113662537/196477339-49e3e4fe-3d92-47c2-b24c-cb84ffe3a99a.png)

3. Floor.java addToUpQueue(), addToDownQueue()
They can be replaced by getUpQueue().add() and getDownQueue().add()
![image](https://user-images.githubusercontent.com/113662537/196477828-e8023adb-27c5-4ad5-979e-d2fb879da6c7.png)

**Comment by oliver-ckl** [comment]
Removed
