### ISSUE TITLE
First passenger's weight larger than the capacity will result in continuous loop until 23:59:59

### ISSUE THREAD

**Issue by WingkeyWinky** [CS3343Group20/Project#14]
The default weight cap is 120kg for a lift, after a new input of 

![螢幕擷取畫面 2022-11-22 161823](https://user-images.githubusercontent.com/98678124/203261547-b9fab0a3-f9c0-4cc0-a864-f006a1d79585.jpg)

The weight of the passenger is more than the capacity of the lift and results in continuously ignoring the request and loop until 23:59:59
![image](https://user-images.githubusercontent.com/98678124/203266582-177196b8-9d5a-4ea7-8909-722b39d7dbc1.png)

Maybe a new exception is needed if the initial passenger's weight is more than the capacity.
(msg: "Please enter a weight less than the capacity" ???)

**Comment by WingkeyWinky** [comment]
Tried other inputs and if one of the passenger's weight is over 120kg(capacity), 
![image](https://user-images.githubusercontent.com/98678124/203271001-1ce488bb-ea5b-455c-a9ad-2499b254c3ea.png)

it will make the two lifts take turns ignoring the request and pass the request to another lift and loop infinitely until 23:59:59
![image](https://user-images.githubusercontent.com/98678124/203271351-96d568ee-4095-498a-a98f-26f495ae56f2.png)
![image](https://user-images.githubusercontent.com/98678124/203271471-73a7802e-b86b-4684-827b-6658f128a08d.png)

**Comment by oliver-ckl** [comment]
Update initial lift capacity to 1000kg so that it fits normal world, i think human in reality will not have 1001kg
