### ISSUE TITLE
lift assign issue

### ISSUE THREAD

**Issue by yoyo200181** [CS3343Group20/Project#8]
![WhatsApp Image 2022-10-13 at 3 58 03 PM](https://user-images.githubusercontent.com/113662537/195549492-248e7293-c995-4e7b-9624-11d19cb7af69.jpeg)

After lift 0 dropped the 1st passenger on 4/F at 01:23:49, lift 0 went back to 0/F. 

Moreover, lift 1 went up and dropped down 2nd passenger on 5/F at **01:23:51** meanwhile lift 0 was moving down to 0/F from 1/F. In this case, lift 1 should keep going up to 6/F and load the 3rd passenger because request 3 was already received at **01:23:50**. 

However, lift 1 went back to 0/F after dropping down 2nd passenger. And the 3rd passenger needed to wait for lift 0 to go up to 6/F after it went back to 0/F.

![image](https://user-images.githubusercontent.com/113662537/195552954-81c013b3-637f-4ebe-8866-3f82b08c958d.png)
![image](https://user-images.githubusercontent.com/113662537/195553099-261f1bbf-fd69-44de-818f-968d20d1a686.png)
![image](https://user-images.githubusercontent.com/113662537/195553186-df2c5521-b5f3-4ec4-9c34-cd442d2c790f.png)
![image](https://user-images.githubusercontent.com/113662537/195553292-559f39df-1cb2-45c1-8cfb-6a0800487610.png)
![image](https://user-images.githubusercontent.com/113662537/195553344-8e7f02b6-a90b-46b1-8d49-f00ef64ed1ae.png)

**Comment by oliver-ckl** [comment]
solved
